name: EV-cli build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./ev-cli
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./ev-cli
      run: cargo test --verbose
